apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hindsight.fullname" . }}-acquire
  labels:
    {{- include "hindsight.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.acquire.replicaCount }}
  selector:
    matchLabels:
      app: hindsight-acquire
      {{- include "hindsight.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: hindsight-acquire
        {{- include "hindsight.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "hindsight.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-acquire
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          command:
            - acquire/bin/acquire
            - start
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PRESTO_URL
              value: http://{{ template "kdp.presto.fullname" . }}:{{ .Values.presto.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
